// Generated by CoffeeScript 1.9.1
(function() {
  var MudServer;

  MudServer = (function() {
    function MudServer() {}

    MudServer.prototype.start = function(socket) {};

    return MudServer;

  })();

  module.exports = MudServer;

}).call(this);
